### ISSUE TITLE
Fails to install on mac osx node 8.0.0

### ISSUE THREAD

**Issue by iddolazar** [jruizgit/rules#132]
Hi,
npm install fails on my machine with node 8.0.0.
Should I change something? will code be updated to support newer versions as I only see issues opened & fixed for version 4.x..

Log:
1647 verbose stack Error: durable@0.36.80 install: `node-gyp rebuild`
1647 verbose stack Exit status 1
1647 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
1647 verbose stack     at emitTwo (events.js:125:13)
1647 verbose stack     at EventEmitter.emit (events.js:213:7)
1647 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1647 verbose stack     at emitTwo (events.js:125:13)
1647 verbose stack     at ChildProcess.emit (events.js:213:7)
1647 verbose stack     at maybeClose (internal/child_process.js:887:16)
1647 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
1648 verbose pkgid durable@0.36.80
1649 verbose cwd /Users/iddo/Development/server
1650 verbose Darwin 17.3.0
1651 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "durable" "--save"
1652 verbose node v8.0.0
1653 verbose npm  v5.4.1

Thanks.

**Comment by iddolazar** [comment]
was able to install after adding
**_--unsafe-perm_**
to npm install.....

any nicer solution or is this one ok?

**Comment by jruizgit** [comment]
Hi, tanks for reporting this issue. Let me look for a better solution. I will report back in a couple of days.

**Comment by iddolazar** [comment]
Many thanks.

**Comment by vbabenko** [comment]
@jruizgit Hi,
Do you have any updates here?
