### ISSUE TITLE
Durable is unable to connect to server ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Kasuhikdas** [jruizgit/rules#144]
r.bindRuleset(handle, db.host, db.port, db.password, db.db);
                      ^

Error: Could not create connection, error code: 301
    at Object.that.bind (/home/kaushikdas/rules/node_modules/durable/libjs/durableEngine.js:435:23)
    at Object.that.registerRulesets (/home/kaushikdas/rules/node_modules/durable/libjs/durableEngine.js:1180:39)
    at createHost (/home/kaushikdas/rules/node_modules/durable/libjs/durable.js:1865:19)
    at Object.runAll (/home/kaushikdas/rules/node_modules/durable/libjs/durable.js:1880:25)
    at Object.<anonymous> (/home/kaushikdas/rules/durable2.js:14:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3

Getting this error whenever i am executing the file.

**Comment by jruizgit** [comment]
Hi, thank you for posting the question. Error code 301 means the redis connection could not be established. I have documented the list of error codes here:

https://github.com/jruizgit/rules/blob/master/docs/js/reference.md#error-codes

If you are using a redis server outside your box, you need to provide the address as follows:

```javascript
var d = require('durable');
d.ruleset('a0', function() {
    whenAll: m.amount < 100
    run: console.log('a0 approved')
  
    whenStart: {
        post('a0', { amount: 10 });
    }
});
d.runAll([{host: 'hostName', port: port, password: 'password'}]);
```
