### ISSUE TITLE
Issue with delete state

### ISSUE THREAD

**Issue by allen7593** [jruizgit/rules#149]
Hi I was getting an error when I try to delete the state after I retrieved it, Here is the error message I got:

```
Connected to pydev debugger (build 173.4674.37)
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
{'subject': 'World', 'agenda_group': 'pre_app_change', 'domain_id': '1', 'sid': 0}
{'sid': '0', 'result': '1'}
127.0.0.1 - - [24/Mar/2018 00:03:17] "POST /rule_entry HTTP/1.1" 200 -
127.0.0.1 - - [24/Mar/2018 00:03:18] "POST /rule_entry HTTP/1.1" 200 -
{'subject': 'World', 'agenda_group': 'pre_app_change', 'domain_id': '13', 'sid': 21}
{'sid': '21', 'result': '2'}
{'subject': 'World', 'agenda_group': 'pre_app_change', 'domain_id': '1', 'sid': 0}
[2018-03-24 00:03:22,088] ERROR in app: Exception on /rule_entry [POST]
Traceback (most recent call last):
  File "C:\Users\allen\PycharmProjects\backend\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\allen\PycharmProjects\backend\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\allen\PycharmProjects\backend\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\allen\PycharmProjects\backend\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\allen\PycharmProjects\backend\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\allen\PycharmProjects\backend\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/allen/PycharmProjects/backend/app.py", line 17, in rule_entry
    result = host.get_state(message["agenda_group"], message["sid"])
  File "C:\Users\allen\PycharmProjects\backend\venv\lib\site-packages\durable\engine.py", line 971, in get_state
    return self.get_ruleset(ruleset_name).get_state(sid)
  File "C:\Users\allen\PycharmProjects\backend\venv\lib\site-packages\durable\engine.py", line 505, in get_state
    return json.loads(rules.get_state(self._handle, sid))
rules.error: Could not get state, error code: 305
127.0.0.1 - - [24/Mar/2018 00:03:22] "POST /rule_entry HTTP/1.1" 500 -
start action base exception type <class 'TypeError'>, value the JSON object must be str, bytes or bytearray, not 'NoneType', traceback ['  File "C:\\*\\PycharmProjects\\backend\\venv\\lib\\site-packages\\durable\\engine.py", line 573, in dispatch\n    state = json.loads(result[0])\n', '  File "C:\\Python\\Python36\\lib\\json\\__init__.py", line 348, in loads\n    \'not {!r}\'.format(s.__class__.__name__))\n']
Exiting the JSON object must be str, bytes or bytearray, not 'NoneType'

Process finished with exit code 1
```

and I have to restart redis to enable the server
Here is the test code I've written that will reproduce this problem
trigger
```python
@app.route('/rule_entry', methods=["POST", ])
def rule_entry():
    message = json.loads(request.stream.read())
    print(message)
    host.post(message["agenda_group"], message)
    # load data
    result = host.get_state(message["agenda_group"], message["sid"])
    print(result)
    host.delete_state(message["agenda_group"], message["sid"])
    return make_response(json.dumps({'outcome': str(result)}))
```

defination
```python
with ruleset("pre_app_change"):
    @when_all(m.subject != "")
    def say_hello(c):
        # consequent
        print('Hello {0}'.format(c.m.subject))
        c.s.result = c.m.domain_id
```

and btw I was running durable_rule on flask
and here is the code I write to post the json
```python
import json

import requests

json_test = {
    'subject': 'World',
    'agenda_group': "pre_app_change",
    'domain_id': '1',
    'sid': 0
}

json_test2 = {
    'subject': 'World',
    'agenda_group': "pre_app_change",
    'domain_id': '13',
    "sid": 21
}

if __name__ == '__main__':
    result = requests.post('http://localhost:5000/rule_entry', json=json_test)
    print(json.loads(result.text))

    result1 = requests.post('http://localhost:5000/rule_entry', json=json_test2)
    print(json.loads(result1.text))

```

**Comment by jruizgit** [comment]
Hi, thanks for reporting the issue. From the error message (and the 305 code), it seems the get_state call is being executed without the state for the "SID" being created. Out of curiosity, what is the outcome of the post call before the failed get_state?

```python
print(host.post(message["agenda_group"], message))
```

**Comment by allen7593** [comment]
Thanks for your quick reply, the result I get before getstate is 0, int type,

**Comment by allen7593** [comment]
![image](https://user-images.githubusercontent.com/5547286/37858582-cdd869c2-2f5a-11e8-9885-327b97d11fe3.png)

**Comment by jruizgit** [comment]
Thanks a lot for reporting the issue. I fixed the bug an uploaded a new version (the engine did not remove the local cache entry after deleting the state in redis). Please use version 0.33.124.

**Comment by allen7593** [comment]
Thanks, I will test it when I get home, I will close this issue after I tried it.

**Comment by allen7593** [comment]
Thanks, it works fine now
