### ISSUE TITLE
Failed to install - mac os node 10.15

### ISSUE THREAD

**Issue by agouz** [jruizgit/rules#181]
Hell team,

I am trying to install durable on MacOs with no success.

```
gyp: Error 1 running xcodebuild
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/eelagouz/.nvm/v0.10.15/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "node" "/Users/eelagouz/.nvm/v0.10.15/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/eelagouz/workspaces/node/durable-rule-engine-test/node_modules/durable
gyp ERR! node -v v0.10.15
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by jruizgit** [comment]
Hi, thanks for reporting the problem. Let me try upgrading my OS X version and I will report back. I assume node.js runs without problems in your box. Is that correct?

**Comment by agouz** [comment]
yep.
MacOS Sierra 10.12.6

**Comment by jruizgit** [comment]
Hi, downloading in MacOS 10.12 and 10.14 works. The node version I'm using is 8.12.0 and npm 3.8.0. looking at the error above, your node and npm version seems a little old. Would you mind verifying?

**Comment by agouz** [comment]
Working now with latest version of durable, thanks :)
