### ISSUE TITLE
Unable to install on Mac os 

### ISSUE THREAD

**Issue by nitinsh99** [jruizgit/rules#186]
Hi there, I am not able to install package on my machine. My configuration:
1. Mac os 10.14
2. Node v11.2.0
3. npm v6.4.1
4. latests xcode command line tools

```
../src/rulesjs/rules.cc:973:17: error: no member named 'SetNamedPropertyHandler' in 'v8::ObjectTemplate'
    proxyTempl->SetNamedPropertyHandler(Get, Set);
    ~~~~~~~~~~  ^
125 warnings and 1 error generated.
make: *** [Release/obj.target/rulesjs/src/rulesjs/rules.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /testapp/node_modules/durable
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ruleengine@1.0.0 No description
npm WARN ruleengine@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! durable@0.36.92 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the durable@0.36.92 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by nimonika** [comment]
I have the exact same issues on my Mac
