### ISSUE TITLE
ReferenceError: sid is not defined 

### ISSUE THREAD

**Issue by enriched** [jruizgit/rules#19]
When I try to compare state to other state using the TypeScript abstraction, `finish: { whenAny: s['count'].gt(s['limit']) }` I get the following stacktrace.

**Stack Trace:**
```
ReferenceError: sid is not defined
    at Object.that.define (/Users/enriched/git/scratch/node_modules/durable/libjs/durable.js:142:21)
    at Object.that.define (/Users/enriched/git/scratch/node_modules/durable/libjs/durable.js:150:45)
    at Object.that.define (/Users/enriched/git/scratch/node_modules/durable/libjs/durable.js:390:41)
    at Object.that.define (/Users/enriched/git/scratch/node_modules/durable/libjs/durable.js:810:30)
    at Object.that.define (/Users/enriched/git/scratch/node_modules/durable/libjs/durable.js:853:52)
    at Object.that.define (/Users/enriched/git/scratch/node_modules/durable/libjs/durable.js:906:64)
    at module.exports.createHost (/Users/enriched/git/scratch/node_modules/durable/libjs/durable.js:931:62)
    at Object.module.exports.runAll (/Users/enriched/git/scratch/node_modules/durable/libjs/durable.js:951:25)
    at Object.<anonymous> (/Users/enriched/git/scratch/built/index.js:57:11)
    at Module._compile (module.js:425:26)
```

When I change to `finish: { whenAny: s['count'].gt(10) }` it works as expected.

**Comment by jruizgit** [comment]
Hi Rich, I'm sorry for taking so long on my reply. Can you please try writing the expression above as follows?

`finish: { whenAny: s['count'].gt(c.s['limit']) }`

Please note the `c.s`. In your case the code should be throwing a meaningful exception. I will fix that.

**Comment by enriched** [comment]
Hi Jesus, thanks for the reply and sorry for the false alarm.  Using c.s appears to work, although the c.s generates an error in Typescript because 's' doesn't exist on the Model type.  I can do (c as any).s['limit'] for now and should be able to move forward 👍
