### ISSUE TITLE
Not working with MacOS or Docker

### ISSUE THREAD

**Issue by jfelten** [jruizgit/rules#193]
I tried running durable locally in nodejs on my Mac:
I was able to install via npm install durable --save my mac running: 10.13.6, but the js hello-world example didn't start locally:

Error: Could not create connection, error code: 301
    at Object.that.bind (/Users/jfelten/git/jfelten/minecraftBots/node_modules/durable/libjs/durableEngine.js:435:23)
    at Object.that.registerRulesets (/Users/jfelten/git/jfelten/minecraftBots/node_modules/durable/libjs/durableEngine.js:1180:39)
    at createHost (/Users/jfelten/git/jfelten/minecraftBots/node_modules/durable/libjs/durable.js:1886:19)
    at Object.runAll (/Users/jfelten/git/jfelten/minecraftBots/node_modules/durable/libjs/durable.js:1901:25)
    at Object.<anonymous> (/Users/jfelten/git/jfelten/minecraftBots/src/rules/guard-rules.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

So I figured ok let's try running on docker/linux:

 docker run -it node bash
# npm init
# npm install durable
<LOTS_OF_ERRORS> due to c lib incompatibility
node --version
v11.10.0

Is there a known working OS/node.js version?   I'm happy to contribute a dockerfile if interested.

**Comment by jfelten** [comment]
retried with node:8 and it works.  I didn't realize durable also needs a running instance of redis to start - so will reply back.

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. It would be great if you can contribute the docker file. I'm working on the second version of durable_rules (estimate completing it by June 2019), it will have the ability to work without redis.
