### ISSUE TITLE
An exception occurred when requesting the same assertion

### ISSUE THREAD

**Issue by lemonhu** [jruizgit/rules#250]
When two identical assertions are requested, it has an `MessageObservedException` exception. The sample code is as follows:
```Python
from durable.lang import *

with ruleset('animal'):
    # will be triggered by 'Kermit eats flies'
    @when_all((m.predicate == 'eats') & (m.object == 'flies'))
    def frog(c):
        c.assert_fact({ 'subject': c.m.subject, 'predicate': 'is', 'object': 'frog' })

    @when_all(+m.subject)
    def output(c):
        print('Fact: {0} {1} {2}'.format(c.m.subject, c.m.predicate, c.m.object))

assert_fact('animal', { 'subject': 'Kermit', 'predicate': 'eats', 'object': 'flies' })
assert_fact('animal', { 'subject': 'Kermit', 'predicate': 'eats', 'object': 'flies' })
```
The output is as follows:

> Fact: Kermit is frog
Fact: Kermit eats flies
Traceback (most recent call last):
  File "facts.py", line 14, in <module>
    assert_fact('animal', { 'subject': 'Kermit', 'predicate': 'eats', 'object': 'flies' })
  File "/Users/hzq/.conda/envs/py3.6/lib/python3.6/site-packages/durable/lang.py", line 671, in assert_fact
    return get_host().assert_fact(ruleset_name, fact, complete)
  File "/Users/hzq/.conda/envs/py3.6/lib/python3.6/site-packages/durable/engine.py", line 763, in assert_fact
    return self._handle_function(rules, rules.assert_fact, fact, complete)
  File "/Users/hzq/.conda/envs/py3.6/lib/python3.6/site-packages/durable/engine.py", line 736, in _handle_function
    rules.do_actions(func(args), callback)
  File "/Users/hzq/.conda/envs/py3.6/lib/python3.6/site-packages/durable/engine.py", line 330, in assert_fact
    return self._handle_result(rules.assert_fact(self._handle, json.dumps(fact, ensure_ascii=False)), fact)
  File "/Users/hzq/.conda/envs/py3.6/lib/python3.6/site-packages/durable/engine.py", line 319, in _handle_result
    raise MessageObservedException(message)
durable.engine.MessageObservedException: {'subject': 'Kermit', 'predicate': 'eats', 'object': 'flies'}

The same assertion request should return the same result, but why is there an exception? I am confused about this and look forward to your answer.

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. The reason is because the second fact will not be evaluated nor stored, as the engine data structures don't support holding identical facts. For your case above, you can disambiguate the facts by using an id:

```python
from durable.lang import *

with ruleset('animal'):
    # will be triggered by 'Kermit eats flies'
    @when_all((m.predicate == 'eats') & (m.object == 'flies'))
    def frog(c):
        c.assert_fact({ 'subject': c.m.subject, 'predicate': 'is', 'object': 'frog', 'thread_id': c.m.thread_id})

    @when_all(+m.subject)
    def output(c):
        print('Fact: {0} {1} {2}'.format(c.m.subject, c.m.predicate, c.m.object))

assert_fact('animal', { 'subject': 'Kermit', 'predicate': 'eats', 'object': 'flies', 'thread_id': 1 })
assert_fact('animal', { 'subject': 'Kermit', 'predicate': 'eats', 'object': 'flies', 'thread_id': 2 })
```

**Comment by lemonhu** [comment]
Thank you very much for your answers.
It would be nice if the system supports requesting the same assertions without using an extra ID.
