### ISSUE TITLE
When I call rule engine with thread, At times I met [rules.error] exception.

### ISSUE THREAD

**Issue by maifire** [jruizgit/rules#291]
Hi, Thank for your previous answer.
When I call rule engine with thread, At times I met next error(Especially at first thread)

_base exception type <class 'rules.error'>, value Could not complete and start action, error code: 307, traceback ['  File "C:\\Python\\lib\\site-packages\\durable\\engine.py", line 451, in action_callback\n    new_result = rules.complete_and_start_action(self._handle, c._handle)\n']
Exception in thread Thread-62:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "profile_consumer_test_thread.py", line 223, in subscribe_redis
    get_profile(myip, mytime)
  File "profile_consumer_test_thread.py", line 141, in get_profile
    post('ato_system', {'fail_rate': fail_rate, 'try_count': try_count, 'distinct_id_rate': distinct_id_rate, 'dummy': 1})
  File "C:\Python\lib\site-packages\durable\lang.py", line 666, in post
    return get_host().post(ruleset_name, message, complete)
  File "C:\Python\lib\site-packages\durable\engine.py", line 786, in post
    return self._handle_function(rules, rules.assert_event, message, complete)
  File "C:\Python\lib\site-packages\durable\engine.py", line 772, in _handle_function
    raise error[0]
  File "C:\Python\lib\site-packages\durable\engine.py", line 451, in action_callback
    new_result = rules.complete_and_start_action(self._handle, c._handle)
rules.error: Could not complete and start action, error code: 307
elapsed time: 0.03260229999999997 (Other thread run successfully)
elapsed time: 0.03268509999999991
elapsed time: 0.03301439999999989_

My Testing Code is below(I leaved out some detailed code for readability).
I am afraid that if I have used thread unsafely.
Thank for your help.

`from rediscluster import RedisCluster
import pandas
from datetime import datetime, timedelta
from collections import Counter
from durable.lang import *
from pymongo import MongoClient
import time
import threading

startup_nodes = [{"host": "xxx.xxx.xxx.xxx", "port": "6379"}, {"host": "xxx.xxx.xxx.xxx", "port": "6379"}]
rc = RedisCluster(startup_nodes=startup_nodes, decode_responses=True)

def add_list_to_set(my_list, my_set):
    [my_set.add(each) for each in my_list]
    return my_set
    
def detect_callback(c):
    if(debug):
        print('detected')
        print(str(c.m.fail_rate) + ' ' + str(c.m.try_count) + ' ' + str(c.m.distinct_id_rate))
    
    # insert data into mongodb
    set_detect_info(c.m.fail_rate, c.m.try_count, c.m.distinct_id_rate)
    
def safe_callback(c):
    if(debug):
        print('safe')

dynamic_ruleset = { 'ato_system': {
    'suspect': {
        'run': detect_callback,
        'all': [
            {'m': {
                "$and": [
                        {
                           '$gte': {'fail_rate': 0.33}
                        },                
                        {
                           '$gte': {'try_count': 112}
                        },
                        {
                           '$gte': {'distinct_id_rate': 0.35}
                        },
                        ]
                  }
            }
        ],
    },    
    'pass': {
        'run': safe_callback,
        'all': [
            {'m': {'$eq': {'dummy': 1}}}
        ],
    }
}}

get_host().set_rulesets(dynamic_ruleset)

# Get summary from redis and call durable rules
def get_profile(myip, mytime):
    ...

    c = Counter()
    p = rc.pipeline()

    # get summary from redis
    for time in time_range:
        p.hgetall(my_ip + ":" + str(time)[:-3].replace(' ', '-').replace(':', '-') + ":" + count_suffix)
        
    for h in p.execute():
        for keys in h: 
            h[keys] = int(h[keys]) 
        c.update(h)

    succ_count = int(c["Succ"])
    ....
    
    post('ato_system', {'fail_rate': fail_rate, 'try_count': try_count, 'distinct_id_rate': distinct_id_rate, 'dummy': 1})

# set full log to mongodb
def set_loginlog(myip, myid, myresult, mypcid, mytime):
    ...

# set detect log to mongodb
def set_detect_info(fail_rate, try_count, distinct_id_rate):
    ...

    
# Redis Streams Version Consumer
def subscribe_redis():
    stream_name = "stream_test"
    group_name = "peterpan"
    consumer_name = "peter"
    
    # bring task from redis stream
    item = rc.xreadgroup(group_name, consumer_name, {stream_name:">"}, count=1)
    
    message = {}
    
    if item:
        message = item[0][1][0][1]
        
        ...
        
        # redis summary update
        rc.hincrby(hashname_count, key, n)
        rc.sadd(hashname_distinct, myid)

        # get summary
        get_profile(myip, mytime)
        
        # set full log to mongodb
        set_loginlog(myip, myid, myresult, mypcid, mytime)

if __name__ == "__main__":
    threads = list()
    for index in range(1):
        for index in range(100):
            x = threading.Thread(target=subscribe_redis)
            threads.append(x)
            x.start()`

**Comment by jruizgit** [comment]
Hi, thanks for reporting this issue. This is a good catch. The rules engine was not locking the context correctly when dispatching an actions after switching thread context. I have published a fix. Please use version 2.0.17
