### ISSUE TITLE
JSON Syntax for statechart

### ISSUE THREAD

**Issue by ss7gowda** [jruizgit/rules#313]
Hello

I'm trying to work through the JSON syntax, but not having much luck with Statecharts.  

Is there a simple example of a statechart in JSON syntax?  I'm trying w/ and w/o JSON syntax.  I'm trying with both function references and inline function declaration.  Both are failing with the same error, so I suspect some issue with JSON structure:

```
var d = require('durable')

d.statechart('risk', function() {
  start: {
    to: 'exit'
    run: console.log('inside start')
  }
  exit: {}
})

var ruleset = {
  'jsonrisk': {
    'start': {
      't_0': {
        'to': 'exit',
        'run': function(c) { console.log('json: inside start') }
        //'run': 'printRisk'
      }
    },
    'exit': {}
  }
}

var h = d.getHost()
h.getAction = function(actionName) {
  if(actionName === 'printRisk') {
    return function(c) {
      //testRisk(c)
      console.log('printRisk')
    }
  }
}

h.setRulesets(ruleset, function(err, res) {
  if(err) {
    console.log("ERROR: ", err)
  }
})

console.log(h.getRuleset('risk').getDefinition())

console.log(h.getRuleset('jsonrisk').getDefinition())
```

The above code gives me the following error:

```
ERROR:  TypeError: Cannot read property 'continueWith' of undefined
    at ruleset (/home/sgowda/dev/att/smet/node_modules/durable/libjs/durableEngine.js:460:33)
    at createRulesets (/home/sgowda/dev/att/smet/node_modules/durable/libjs/durableEngine.js:785:38)
    at Object.that.registerRulesets (/home/sgowda/dev/att/smet/node_modules/durable/libjs/durableEngine.js:858:28)
    at Object.that.setRulesets (/home/sgowda/dev/att/smet/node_modules/durable/libjs/durableEngine.js:847:22)
    at Object.<anonymous> (/home/sgowda/dev/att/smet/t01.js:35:3)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
{
  start: { t_0: { to: 'exit', run: [Function: run] } },
  exit: {},
  '$type': 'stateChart'
}

/home/sgowda/dev/att/smet/node_modules/durable/libjs/durableEngine.js:839
                throw 'Ruleset ' + rulesetName + ' not found';
                ^
Ruleset jsonrisk not found
````

Thanks.

**Comment by ss7gowda** [comment]
Hello,

Sorry - this was user error.  I needed to use "jsonrisk$state" instead of "jsonrisk".

Thanks.
