### ISSUE TITLE
is it possible to check if anyItem is false in Python?

### ISSUE THREAD

**Issue by ehrenb** [jruizgit/rules#336]
In the Python bindings, is it possible to check if the anyItem call returns False?  

I have the following example to demonstrate. I want to be able to check when a person has changed the name for a pet to 'spot'.  In this example, I pass two states to the engine, the previous (containing an old nickname, 'max') and a new (containing a new nickname 'spot'):

```python
import logging

import durable
from durable.lang import *

logging.basicConfig()
logger = logging.getLogger()
logger.setLevel(logging.INFO)

with ruleset('rules'):

    @when_all(
        not (m.previous.pets.anyItem((item.nickname == 'spot') &
                                     (item.type.matches('dog')))
            ) &
        (m.new.pets.anyItem((item.nickname == 'spot') &
                            (item.type.matches('dog')))
        ))
    def new_name(c):
        logger.info("new nickname")


def run(fact):
    assert_fact('rules', fact)
    facts = get_facts("rules")
    logger.info(facts)
    return facts


if __name__ == '__main__':

    previous = {
        'name': 'bob',
        'pets': [
            {
                'nickname': 'max',
                'type': 'dog'
            }
        ]
    }

    new = {
        'name': 'bob',
        'pets': [
            {
                'nickname': 'spot',
                'type': 'dog'
            }
        ]
    }

    fact = {
        'previous': previous,
        'new': new
    }
    try:
        run(fact)
    except durable.engine.MessageNotHandledException as e:
        logger.error('Unsupported fact', exc_info=True)
```

When run, returns:

```
Traceback (most recent call last):
  File "testrules.py", line 60, in <module>
    run(fact)
  File "testrules.py", line 27, in run
    assert_fact('rules', fact)
  File "/home/branden/venvs/durable-test/lib/python3.6/site-packages/durable/lang.py", line 676, in assert_fact
    return get_host().assert_fact(ruleset_name, fact, complete)
  File "/home/branden/venvs/durable-test/lib/python3.6/site-packages/durable/engine.py", line 817, in assert_fact
    return self._handle_function(rules, rules.assert_fact, fact, complete)
  File "/home/branden/venvs/durable-test/lib/python3.6/site-packages/durable/engine.py", line 790, in _handle_function
    rules.do_actions(func(args), callback)
  File "/home/branden/venvs/durable-test/lib/python3.6/site-packages/durable/engine.py", line 343, in assert_fact
    return self._handle_result(durable_rules_engine.assert_fact(self._handle, json.dumps(fact, ensure_ascii=False)), fact)
  File "/home/branden/venvs/durable-test/lib/python3.6/site-packages/durable/engine.py", line 328, in _handle_result
    raise MessageNotHandledException(message)
durable.engine.MessageNotHandledException: {'previous': {'name': 'bob', 'pets': [{'nickname': 'max', 'type': 'dog'}]}, 'new': {'name': 'bob', 'pets': [{'nickname': 'spot', 'type': 'dog'}]}}
```

My assumption here is that anyItem doesn't actually return a conditional, so checking 'not', or '== False' won't work.  Is this possible to get to work? Using durable-rules version 2.0.28.

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. durable_rules doesn't have a 'not' operator. Try doing `pets.allItems(item.nickname != 'spot')` .

**Comment by ehrenb** [comment]
Thanks, as a follow up question: is it possible to compare a list length within the rule decorator? for example, if bob didn't own any pets previously:

```python
    previous = {
        'name': 'bob',
        'pets': []
    }
...

I understand that '+' and '-' are overloaded for checking existence of keys, so it seems possible as long as my data is enforced to always have at least one element in the list when the key 'pets' exists, or no 'pets' key at all if no elements in the list.  Just wondering if there's a cleaner approach.
