### ISSUE TITLE
(ruby) Complex rule not working

### ISSUE THREAD

**Issue by mrryanjohnston** [jruizgit/rules#344]
I want to create a rule that performs an action if a point is inside of a circle. Something like:

```ruby
Durable.ruleset :circle do
  when_all(
    c.circle = (+m.x) & (+m.y) & (+m.radius),
    c.other_circle = (+m.x) & (+m.y) & (
      circle.radius * circle.radius > (
        ( (m.x - circle.x) * (m.x - circle.x) )
        +
        ( (m.y - circle.y) * (m.y - circle.y) )
      ) * (
        ( (m.x - circle.x) * (m.x - circle.x) )
        +
        ( (m.y - circle.y) * (m.y - circle.y) )
      )
    )
  ) do
    puts "the center of circle #{other_circle.name} " \
      "is inside of circle #{circle.name}"
  end
end

Durable.assert :circle, { name: :a, radius: 100, x: 0, y: 0 }
Durable.assert :circle, { name: :b, radius: 1, x: 5, y: 5 }
```

This gives me an error:

```
$ ruby test.rb
Traceback (most recent call last):
        7: from test.rb:3:in `<main>'
        6: from /home/ryan/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/durable_rules-2.0.27/librb/durable.rb:66:in `ruleset'
        5: from /home/ryan/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/durable_rules-2.0.27/librb/durable.rb:66:in `new'
        4: from /home/ryan/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/durable_rules-2.0.27/librb/durable.rb:425:in `initialize'
        3: from /home/ryan/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/durable_rules-2.0.27/librb/durable.rb:425:in `instance_exec'
        2: from test.rb:6:in `block in <main>'
        1: from /home/ryan/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/durable_rules-2.0.27/librb/durable.rb:304:in `&'
/home/ryan/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/durable_rules-2.0.27/librb/durable.rb:336:in `merge': Right type doesn't match (ArgumentError)
```

I try to change the rule to this:

```ruby
Durable.ruleset :circle do
  when_all(
    c.circle = (+m.x) & (+m.y) & (+m.radius),
    c.other_circle = (+m.x) & (+m.y) & (
      (
        ( (m.x - circle.x) * (m.x - circle.x) )
        +
        ( (m.y - circle.y) * (m.y - circle.y) )
      ) * (
        ( (m.x - circle.x) * (m.x - circle.x) )
        +
        ( (m.y - circle.y) * (m.y - circle.y) )
      ) <= circle.radius * circle.radius
    )
  ) do
    puts "the center of circle #{other_circle.name} " \
      "is inside of circle #{circle.name}"
  end
end

Durable.assert :circle, { name: :a, radius: 100, x: 0, y: 0 }
Durable.assert :circle, { name: :b, radius: 1, x: 5, y: 5 }
```

But this gives me no output.

I try to change this to something smaller:

```ruby
require "durable"

Durable.ruleset :circle do
  when_all(
    c.circle = (+m.x) & (+m.y) & (+m.radius),
    c.other_circle = (+m.x) & (+m.y) & (
      (
        ( (m.x - circle.x) * (m.x - circle.x) )
      ) <= circle.radius
    )
  ) do
    puts "the center of circle #{other_circle.name} " \
      "is inside of circle #{circle.name}"
  end
end

Durable.assert :circle, { name: :a, radius: 100, x: 0, y: 0 }
Durable.assert :circle, { name: :b, radius: 1, x: 5, y: 5 }
```

but this also gives me no output.

I try changing this to something smaller:

```ruby
require "durable"

Durable.ruleset :circle do
  when_all(
    c.circle = (+m.radius),
    c.other_circle = (
      (
        ( (m.x - circle.x) )
      ) <= circle.radius
    )
  ) do
    puts "the center of circle #{other_circle.name} " \
      "is inside of circle #{circle.name}"
  end
end

Durable.assert :circle, { name: :a, radius: 100, x: 0, y: 0 }
Durable.assert :circle, { name: :b, radius: 1, x: 5, y: 5 }
```

and this produces this output:

```
$ ruby test.rb
the center of circle a is inside of circle b
the center of circle b is inside of circle a
```

This also gives me output:

```ruby
require "durable"

Durable.ruleset :circle do
  when_all(
    c.circle = (+m.radius),
    c.other_circle = (
      (
        ( (m.x * m.x) )
      ) <= circle.radius
    )
  ) do
    puts "the center of circle #{other_circle.name} " \
      "is inside of circle #{circle.name}"
  end
end

Durable.assert :circle, { name: :a, radius: 100, x: 0, y: 0 }
Durable.assert :circle, { name: :b, radius: 1, x: 5, y: 5 }
```

```
$ ruby test.rb
the center of circle a is inside of circle b
the center of circle b is inside of circle a
```

However, adding a subtraction to that gives me no output:

```ruby
require "durable"

Durable.ruleset :circle do
  when_all(
    c.circle = (+m.radius),
    c.other_circle = (
      (
        ( (m.x * m.x) - 0 )
      ) <= circle.radius
    )
  ) do
    puts "the center of circle #{other_circle.name} " \
      "is inside of circle #{circle.name}"
  end
end

Durable.assert :circle, { name: :a, radius: 100, x: 0, y: 0 }
Durable.assert :circle, { name: :b, radius: 1, x: 5, y: 5 }
```

This also gives me no output:

```ruby
require "durable"

Durable.ruleset :circle do
  when_all(
    c.circle = (+m.radius),
    c.other_circle = (
      (
        ( (m.x * m.x) * 1 )
      ) <= circle.radius
    )
  ) do
    puts "the center of circle #{other_circle.name} " \
      "is inside of circle #{circle.name}"
  end
end

Durable.assert :circle, { name: :a, radius: 100, x: 0, y: 0 }
Durable.assert :circle, { name: :b, radius: 1, x: 5, y: 5 }
```

**Comment by mrryanjohnston** [comment]
Follow-up: This also produces no output:

```ruby
require "durable"

Durable.ruleset :circle do
  when_all(
    c.circle = (+m.radius),
    c.other_circle = (
     circle.radius >
      (
        ( (m.x * m.x) )
      )
    )
  ) do
    puts "the center of circle #{other_circle.name} " \
      "is inside of circle #{circle.name}"
  end
end

Durable.assert :circle, { name: :a, radius: 100, x: 0, y: 0 }
Durable.assert :circle, { name: :b, radius: 1, x: 5, y: 5 }
```

**Comment by mrryanjohnston** [comment]
This is a very curious thing:

```ruby
require "durable"

Durable.ruleset :circle do
  when_all(
    c.circle = (+m.radius),
    c.other_circle = (
     circle.radius >
      (
        (m.x)
      )
    )
  ) do
    puts "the center of circle #{other_circle.name} " \
      "is inside of circle #{circle.name}"
  end
end

Durable.assert :circle, { name: :a, radius: 100, x: 0, y: 0 }
Durable.assert :circle, { name: :b, radius: 1, x: 5, y: 5 }
```

This produces:

```
$ ruby test.rb
the center of circle a is inside of circle b
```

Though given the data, I'd expect both a to be inside of b, and b to be inside of a.

**Comment by mrryanjohnston** [comment]
I think I figured it out! I was reminded of a square plus b squared equals c squared! I think I was thinking about this wrong before. My solution was to make the equation smaller and make it multiple rules:

```ruby
require 'durable'

Durable.ruleset :circle do
  when_all(
    c.point = (+m.x) & (+m.y),
    # a squared plus b squared equals c squared
    c.circle = m.radius * m.radius > ( (point.x * point.x) + (point.y * point.x) )
  ) do
    puts "point #{point.name} " \
      "is inside of circle #{circle.name}"
  end
  when_all(
    c.point = (+m.x) & (+m.y),
    # a squared plus b squared equals c squared
    c.circle = m.radius * m.radius == ( (point.x * point.x) + (point.y * point.x) )
  ) do
    puts "point #{point.name} " \
      "is on the very edge of of circle #{circle.name}"
  end
  when_all(
    c.point = (+m.x) & (+m.y),
    # a squared plus b squared equals c squared
    c.circle = m.radius * m.radius < ( (point.x * point.x) + (point.y * point.x) )
  ) do
    puts "point #{point.name} " \
      "is outside of circle #{circle.name}"
  end
end

Durable.assert :circle, { name: :should_be_inside, x: 0, y: 0 }
Durable.assert :circle, { name: :should_be_outside, x: 101, y: 101 }
Durable.assert :circle, { name: :should_be_on_edge, x: 6, y: 6 }
Durable.assert :circle, { name: :big_circle, radius: 72, x: 0, y: 0 }
```

**Comment by mrryanjohnston** [comment]
I deleted my old comment by accident! I figured out my issue though:

```ruby
require 'durable'

Durable.ruleset :circle do
  when_all(
    c.point = (+m.x) & (+m.y),
    c.circle = m.radius_squared == ( point.x * point.x ) + ( point.y * point.y )
  ) do
    puts "point (#{point.x}, #{point.y}) " \
      "is on the edge of circle #{circle.name}"
  end
  when_all(
    c.point = (+m.x) & (+m.y),
    c.circle = m.radius_squared < ( point.x * point.x ) + ( point.y * point.y )
  ) do
    puts "point (#{point.x}, #{point.y}) " \
      "is outside of circle #{circle.name}"
  end
  when_all(
    c.point = (+m.x) & (+m.y),
    c.circle = m.radius_squared > ( point.x * point.x ) + ( point.y * point.y )
  ) do
    puts "point (#{point.x}, #{point.y}) " \
      "is inside of circle #{circle.name}"
  end
end

Durable.assert :circle, {name: :a, radius_squared: 25, x: 0, y: 0}
Durable.assert :circle, {x: 0, y: 0}
Durable.assert :circle, {x: 1, y: 1}
Durable.assert :circle, {x: -1, y: -1}
Durable.assert :circle, {x: 5, y: -5}
Durable.assert :circle, {x: 5, y: 0}
Durable.assert :circle, {x: 0, y: 5}
Durable.assert :circle, {x: 2, y: 2}
Durable.assert :circle, {x: 3, y: 3}
```
