### ISSUE TITLE
durable_rules_engine.error: Could not create ruleset, error code: 105

### ISSUE THREAD

**Issue by zellelin** [jruizgit/rules#367]
Hi , i've got a ruleset creation problem when test testdynamic.py . and i use mac platform.
```
127.0.0.1 - - [27/Jan/2021 15:49:34] "POST /first/definition HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/Users/linshaoze/learn/code/durable_rule/testpy/testdynamic.py", line 94, in __call__
    return endpoint(environ, start_response, **values)
  File "/Users/linshaoze/learn/code/durable_rule/testpy/testdynamic.py", line 50, in _ruleset_definition_request
    self._host.set_rulesets(ruleset_definition)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/durable/engine.py", line 778, in set_rulesets
    self.register_rulesets(ruleset_definitions)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/durable/engine.py", line 887, in register_rulesets
    rulesets = Ruleset.create_rulesets(self, ruleset_definitions)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/durable/engine.py", line 444, in create_rulesets
    branches[name] = Ruleset(name, host, definition)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/durable/engine.py", line 323, in __init__
    self._handle = durable_rules_engine.create_ruleset(name, json.dumps(ruleset_definition, ensure_ascii=False))
durable_rules_engine.error: Could not create ruleset, error code: 105
```

**Comment by manojkumarsv** [comment]
Generally we may get this error only for large number of rulesets. I'm encountering the same problem with a larger set of rules.  Could you share your solution and the specific changes you made to enable loading a greater number of JSON rules?
