### ISSUE TITLE
Pypi installation issue

### ISSUE THREAD

**Issue by mandecki** [jruizgit/rules#6]
I was able to successfully download and install the package directly form GitHub, but there seems to be an issue with the Pypi durable_rules package (please see errors below).

```
$ sudo pip install durable_rules
Collecting durable-rules
  Downloading durable_rules-0.33.03.tar.gz (83kB)
    100% |████████████████████████████████| 86kB 678kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-0IGFQX/durable-rules/setup.py", line 34, in <module>
        with open(path.join(here, 'README.txt'), encoding='utf-8') as f:
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 884, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/tmp/pip-build-0IGFQX/durable-rules/docs/py/README.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-0IGFQX/durable-rules
```

**Comment by jruizgit** [comment]
Thanks a lot for reporting this problem. I have updated the Python manifest and uploaded a new package to PyPi. It should work now. Please give it another try.
