### ISSUE TITLE
segmentation fault  [python]

### ISSUE THREAD

**Issue by TracyDa** [jruizgit/rules#63]
After I upgrade durable rules to 0.33.89,the code doesn't work on my mac 10.12.2.

> (venv) ➜  python da.py
> [1]    536 segmentation fault  python da.py

So I uninstall it and install durable-rules-0.33.74,it works well.Is this a bug or I need to modify my code?

**Comment by jruizgit** [comment]
Hi, thanks for reporting this. Would you be able to attach the call stack? 

`lldb python da.py`  
`run`  
`bt`

**Comment by jruizgit** [comment]
Quick update on this: I tired mac 10.11.6 and 10.12.3. I used the latest version durable-rules-0.33.90 using python 2.7. All tests passed. Would you mind sharing the code that is failing?

Thanks!

**Comment by inactivist** [comment]
I'm seeing similar issues.  

I installed `faulthandler`[1] and enabled it in order to see the stack trace, which doesn't seem to clarify much:
```python
# test1.py
import faulthandler
from durable.lang import *
faulthandler.enable()

with ruleset('test'):
    @when_all(m.subject == 'World')
    def say_hello(c):
        print ('Hello {0}'.format(c.m.subject))

    @when_start
    def start(host):
        host.post('test', {'id': 1, 'sid': 1, 'subject': 'World'})

run_all()
```

`$ python test1.py`
```
 Fatal Python error: Segmentation fault
Current thread 0x00007fb73a01a700 (most recent call first):
  File "/home/inactivist/.virtualenvs/workflow-view-controller/local/lib/python2.7/site-packages/durable/engine.py", line 409 in bind
  File "/home/inactivist/.virtualenvs/workflow-view-controller/local/lib/python2.7/site-packages/durable/engine.py", line 987 in register_rulesets
  File "/home/inactivist/.virtualenvs/workflow-view-controller/local/lib/python2.7/site-packages/durable/engine.py", line 905 in __init__
  File "/home/inactivist/.virtualenvs/workflow-view-controller/local/lib/python2.7/site-packages/durable/lang.py", line 623 in create_host
  File "/home/inactivist/.virtualenvs/workflow-view-controller/local/lib/python2.7/site-packages/durable/lang.py", line 631 in run_all
  File "test1.py", line 16 in <module>
Segmentation fault
```
## Version info
Ubuntu Linux 15.10 with kernel version 4.4.8, 
Python 2.7.10 in a virtualenv.
durable-rules v0.33.90
redis-server v3.0.7 runnin on port 6379

[1] http://faulthandler.readthedocs.io/

**Comment by inactivist** [comment]
```
$ lldb ~/.virtualenvs/workflow-view-controller/bin/python test1.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lldb.embedded_interpreter
(lldb) target create "/home/inactivist/.virtualenvs/workflow-view-controller/bin/python"
Current executable set to '/home/inactivist/.virtualenvs/workflow-view-controller/bin/python' (x86_64).
(lldb) settings set -- target.run-args  "test1.py"
(lldb) run
Process 12365 launching
Process 12365 launched: '/home/inactivist/.virtualenvs/workflow-view-controller/bin/python' (x86_64)
Process 12365 stopped and restarted: thread 1 received signal: SIGCHLD
Process 12365 stopped
* thread #1: tid = 12365, 0x00007ffff63b7afd rules.so`bindRuleset(handle=0x0000000000000000, host=0x00007ffff7ec6474, port=6379, password=0x0000000000000000, db='\x01') + 29 at net.c:2293, name = 'python', stop reason = invalid address (fault address: 0x78)
    frame #0: 0x00007ffff63b7afd rules.so`bindRuleset(handle=0x0000000000000000, host=0x00007ffff7ec6474, port=6379, password=0x0000000000000000, db='\x01') + 29 at net.c:2293
(lldb) 
```
Python 2.7.10 in virtualenv
Ubuntu 15.10 with Kernel 4.8.8
Redis 2.8 32 bit

**Comment by jruizgit** [comment]
Thanks for posting the callstack. I'll take a look into this and report back.

**Comment by jruizgit** [comment]
I have made a fix and published a new version to pypi. Please try version 0.33.91.

Thanks!

**Comment by inactivist** [comment]
@jruizgit Sample code works here with 0.33.91.  Thanks for the quick turnaround.

**Comment by TracyDa** [comment]
It doesn't work for me.

I run the test python code with my redis config:

`run_all(databases = [{'host': 'localhost', 'port': 9000, 'password':'Abcde@123456', 'db': 0}])`

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    run_all(databases = [{'host': 'localhost', 'port': 9000, 'password':'Abc@123', 'db': 0}])
  File "/Users/tracy/code/venv/lib/python2.7/site-packages/durable/lang.py", line 631, in run_all
    main_host = create_host(databases, state_cache_size)
  File "/Users/tracy/code/venv/lib/python2.7/site-packages/durable/lang.py", line 623, in create_host
    main_host = engine.Host(ruleset_definitions, databases, state_cache_size)
  File "/Users/tracy/code/venv/lib/python2.7/site-packages/durable/engine.py", line 903, in __init__
    self.register_rulesets(None, ruleset_definitions)
  File "/Users/tracy/code/venv/lib/python2.7/site-packages/durable/engine.py", line 985, in register_rulesets
    ruleset.bind(self._databases)
  File "/Users/tracy/code/venv/lib/python2.7/site-packages/durable/engine.py", line 407, in bind
    rules.bind_ruleset(db['password'], db['port'], db['host'], db['db'], self._handle)
rules.error: Could not create connection, error code: 302
Process 32494 exited with status = 1 (0x00000001)
```
It seems that there is something wrong with the redis connection.And I start another redis server without password,it works well.

Maybe the problem is **password**?

**Comment by jruizgit** [comment]
Thanks for providing the stack trace. It seems you got past the seg fault, which is good. Yes 302, means the connection could not be established. Let me debug, I'll report back on my findings.

Sent from my iPhone

On Feb 20, 2017, at 1:45 AM, TracyDa <notifications@github.com<mailto:notifications@github.com>> wrote:


It doesn't work for me.

I run the test python code with my redis config:

run_all(databases = [{'host': 'localhost', 'port': 9000, 'password':'Abcde@123456', 'db': 0}])

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    run_all(databases = [{'host': 'localhost', 'port': 9000, 'password':'Abc@123', 'db': 0}])
  File "/Users/tracy/code/venv/lib/python2.7/site-packages/durable/lang.py", line 631, in run_all
    main_host = create_host(databases, state_cache_size)
  File "/Users/tracy/code/venv/lib/python2.7/site-packages/durable/lang.py", line 623, in create_host
    main_host = engine.Host(ruleset_definitions, databases, state_cache_size)
  File "/Users/tracy/code/venv/lib/python2.7/site-packages/durable/engine.py", line 903, in __init__
    self.register_rulesets(None, ruleset_definitions)
  File "/Users/tracy/code/venv/lib/python2.7/site-packages/durable/engine.py", line 985, in register_rulesets
    ruleset.bind(self._databases)
  File "/Users/tracy/code/venv/lib/python2.7/site-packages/durable/engine.py", line 407, in bind
    rules.bind_ruleset(db['password'], db['port'], db['host'], db['db'], self._handle)
rules.error: Could not create connection, error code: 302
Process 32494 exited with status = 1 (0x00000001)


It seems that there is something wrong with the redis connection.And I start another redis server without password,it works well.

Maybe the problem is password?

**Comment by jruizgit** [comment]
I pushed a fixed to pypi a couple of days ago. The database password information was not being marshaled correctly from python into c. Please try version 0.33.94.

Thanks.

**Comment by TracyDa** [comment]
@jruizgit   Really thanks ,it works well now!
