### ISSUE TITLE
Python API: Mutable default arguments in methods

### ISSUE THREAD

**Issue by Nonisiuniis** [jruizgit/rules#97]
There are several places in the python code where mutable default arguments are used:

engine.py:
```
class Host(object):

    def __init__(self, ruleset_definitions = None, databases = [{'host': 'localhost', 'port': 6379, 'password': None, 'db': 0}], state_cache_size = 1024):
```
```

class Queue(object):

    def __init__(self, ruleset_name, database = {'host': 'localhost', 'port': 6379, 'password':None, 'db': 0}, state_cache_size = 1024):
```

interface.py:
```
class Application(object):

    def __init__(self, host, host_name, port, routing_rules = [], run = None):
```

lang.py:
```
def create_queue(ruleset_name, database = {'host': 'localhost', 'port': 6379, 'password':None, 'db': 0}, state_cache_size = 1024):
```
```
def create_host(databases = [{'host': 'localhost', 'port': 6379, 'password':None, 'db': 0}], state_cache_size = 1024):
```
```
def run_all(databases = [{'host': 'localhost', 'port': 6379, 'password':None, 'db': 0}], host_name = '127.0.0.1', port = 5000, routing_rules = [], run = None, state_cache_size = 1024):
```
```
def run_server(run, databases = [{'host': 'localhost', 'port': 6379, 'password':None, 'db': 0}], routing_rules = [], state_cache_size = 1024):
```

See 
https://docs.python.org/3/reference/compound_stmts.html#function-definitions
and
http://python-guide.readthedocs.io/en/latest/writing/gotchas/

**Comment by jruizgit** [comment]
Hi, this is a good observation. I have reviewed the code paths that use default objects. The object remains immutable, so the usage is OK. 

I'm debating whether I should just stay away from using objects as default values. While it is not necessarily incorrect, it might be difficult to maintain. What do you think?

**Comment by Nonisiuniis** [comment]
There is at least one place in your code where it's not safe:
```
>>> from durable.interface import Application
>>> foo = Application('localhost', 'foo', 123)
>>> bar = Application('localhost, 'bar', 234)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/durable_rules-0.33.111-py3.5-linux-x86_64.egg/durable/interface.py", line 26, in __init__
    self._url_map = Map(routing_rules)
  File "/usr/lib/python3.5/site-packages/werkzeug/routing.py", line 1156, in __init__
    self.add(rulefactory)
  File "/usr/lib/python3.5/site-packages/werkzeug/routing.py", line 1197, in add
    rule.bind(self)
  File "/usr/lib/python3.5/site-packages/werkzeug/routing.py", line 675, in bind
    (self, self.map))
RuntimeError: url rule <Rule '/<ruleset_name>/definition' -> <bound method Application._ruleset_definition_request of <durable.interface.Application object at 0x7f403054a668>>> already bound to map Map([<Rule '/<ruleset_name>/events/<sid>' -> <bound method Application._events_request of <durable.interface.Application object at 0x7f403054a668>>>,
 <Rule '/<ruleset_name>/state/<sid>' -> <bound method Application._state_request of <durable.interface.Application object at 0x7f403054a668>>>,
 <Rule '/<ruleset_name>/facts/<sid>' -> <bound method Application._facts_request of <durable.interface.Application object at 0x7f403054a668>>>,
 <Rule '/<ruleset_name>/definition' -> <bound method Application._ruleset_definition_request of <durable.interface.Application object at 0x7f403054a668>>>,
 <Rule '/<ruleset_name>/events' -> <bound method Application._default_events_request of <durable.interface.Application object at 0x7f403054a668>>>,
 <Rule '/<ruleset_name>/state' -> <bound method Application._default_state_request of <durable.interface.Application object at 0x7f403054a668>>>,
 <Rule '/<ruleset_name>/facts' -> <bound method Application._default_facts_request of <durable.interface.Application object at 0x7f403054a668>>>])
```
You're just appending extra entries to class-level (shared) list on each new instance.

I think the most common way is to replace definitions to something like this:
```
def foo(arg=[]):
    bar
```
becomes
```
def foo(arg=None):
    if arg is None:
        arg = []
    bar
```

**Comment by jruizgit** [comment]
I have removed the mutable objects from argument defaults. 

Thanks for pointing this out.
