### ISSUE TITLE
API isn't decoding properly in Python 3

### ISSUE THREAD

**Issue by grantbachman** [jruizgit/rules#99]
I'm running the application on top of Python 3 and querying it via `curl`, but the application is crashing with the following error:
```
Error on request:
Traceback (most recent call last):
  File "/Users/grant/.virtualenvs/blocks/lib/python3.5/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/Users/grant/.virtualenvs/blocks/lib/python3.5/site-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/Users/grant/.virtualenvs/blocks/lib/python3.5/site-packages/durable/interface.py", line 109, in __call__
    return endpoint(environ, start_response, **values)
  File "/Users/grant/.virtualenvs/blocks/lib/python3.5/site-packages/durable/interface.py", line 97, in _default_facts_request
    message = json.loads(request.stream.read())
  File "/Users/grant/.pyenv/versions/3.5.2/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

This seems to be a simple encoding issue, with Python 2/3 handling string/unicode types differently. It works fine on Python 2.7.

I was able to fix the issue on both Python 2/3 (at least on my machine) by just appending a simple `.decode('utf8')` to the API interface.

Is @jruizgit able to replicate and are you open to PR's? If so, I can write one up and submit it for review.

**Comment by jruizgit** [comment]
Hi, thank you for reporting the problem. Yes, please send me a pull request and I will merge it.

**Comment by jruizgit** [comment]
Hi @grantbachman, I could not repro the problem. I used python 3 in macos platform. What platform are you using? Would you mind pasting your curl command?

I have added the utf-8 decode and uploaded a new version to pypi.

**Comment by grantbachman** [comment]
I'm running Python 3.5.2 on Mac OS. I was just testing with the example located [here](https://github.com/jruizgit/rules/blob/master/docs/py/reference.md#facts). Your newest release (0.33.114) has fixed the decoding issue for me. Thank you!
